meta:
  engine: 4.0.4
  name: samoklava
  version: 0.3
  author: soundmonnster
  url: https://github.com/soundmonster/samoklava
units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
      diode:
        type: diode
        nets:
          from: =colrow
          to: =row_net
        anchor:
          shift: [0, -5]
  zones:
    matrix:
      key.padding: ky
      columns:
        backspace:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_backspace
        caps:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_caps
        pinky:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_pinky
        ring:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_ring
        middle:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_middle
        index:
          key:
            stagger: -0 ky
            spread: kx
            column_net: col_index
        inner:
          key:
            stagger: -0 ky
            spread: kx
            column_net: col_inner
        inner2:
          key:
            stagger: -0 ky
            spread: kx
            column_net: col_inner2
      rows:
        ctrl:
          row_net: row_ctrl
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
        number:
          row_net: row_number
outlines:
  # board dimensions according to JLCPCB: 122.28 mm x 101.05 mm
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kx + px, ky + py]
      corner: px
  # patch_outer:
  #   - what: polygon
  #     points:
  #       - ref: matrix_pinky_top
  #       - ref: matrix_pinky_bottom
  #       - ref: matrix_backspace_bottom
  #         shift: [-0.5 (kx + px), 0]
  #       - ref: matrix_backspace_top
  #         shift: [-0.5 (kx + px), 0]
  # patch_inner:
  #   - what: polygon
  #     points:
  #       - ref: matrix_inner2_top
  #         shift: [0.5 (kx + px), 0]
  #       - ref: matrix_inner2_bottom
  #         shift: [0.5 (kx + px), 0]
  #       - ref: matrix_inner_bottom
  #       - ref: matrix_inner_top
  controller_area:
    - what: rectangle
      where:
        - ref: matrix_inner2_top
          # re-tranalte to new anchor position
          shift: [-56/2 + .5kx + 1, 30/2 + 1.5ky - 3]
      size: [56, 30]
      corner: px
  # patch_controller:
  #   - what: polygon
  #     points:
  #       - ref: controller_area
  #       - ref: matrix_number_top
  #       - ref: matrix_backspace_top
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 14
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [kx, ky] 
      corner: 1
  keywell:
    - "raw"
    # - "+patch_inner"
    # - "+patch_outer"
  base_outline:
    - "keywell"
    - "+controller_area"
    # - "+patch_controller"
  screw_holes:
    top_left:
      what: circle
      where:
        - ref: matrix_ring_home
          shift: [-0.5 kx, 0 ky]
      radius: 1.05
    bottom_left:
      what: circle
      where:
        - ref: matrix_pinky_bottom
          shift: [0.5 kx, 0]
      radius: 1.05
    top_right:
      what: circle
      where:
        - ref: matrix_inner2_top
          shift: [-0.5 kx, 0]
      radius: 1.05
    palm:
      what: circle
      where:
        - ref: matrix_index_bottom
          shift: [0, -1.06 ky]
      radius: 1.05
  mounting_holes:
    $extends: outlines.screw_holes
    top_left:
      radius: 2.05
    bottom_left:
      radius: 2.05
    top_right:
      radius: 2.05
    palm:
      radius: 2.05
  bottom_outline:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-screw_holes"
  plate:
    - "keywell"
    - "-switches"
    - "-screw_holes"
  pcb:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-mounting_holes"
pcbs:
  top_plate:
    outlines:
      edge:
        outline: plate
        layer: Edge.Cuts
    footprints:
      jlc_order_number:
        what: text
        where:
          ref:
            - matrix_ring_home
          shift: [-0.25 kx, 0.5 ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: left
  bottom_plate:
    outlines:
      edge:
        outline: bottom_outline
        layer: Edge.Cuts
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
    footprints:
      choc_hotswap:
        what: choc
        where:
          - /matrix_.*/
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: diode
        where:
          - /matrix_.*/
        adjust.shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      mcu_l:
        what: promicro_flippable
        where:
          ref:
            - matrix_inner2_top
          shift: [-24, 38]
          rotate: 0
        params:
          orientation: up
          P3: row_number
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_ctrl
          P10: col_inner2
          P16: col_inner
          P14: col_index
          P15: col_middle
          P18: col_ring
          P19: col_pinky
          P20: col_caps
          P21: col_backspace
      mcu_r:
        what: promicro_flippable
        where:
          ref:
            - matrix_inner2_top
          shift: [-25.25, 40.5]
          rotate: 0
        params:
          orientation: down
          silk_layer: F.SilkS
      # pad_plus:
      #   what: pad
      #   where:
      #     ref:
      #       - matrix_inner2_top
      #     shift: [-6, 23]
      #     rotate: 0
      #   params:
      #     front: true
      #     back: true
      #     width: 1.5
      #     height: 1.5
      #     text: "B+"
      #     net: Bplus
      # pad_minus:
      #   what: pad
      #   where:
      #     ref:
      #       - matrix_inner2_top
      #     shift: [-3, 23]
      #     rotate: 0
      #   params:
      #     front: true
      #     back: true
      #     width: 1.5
      #     height: 1.5
      #     text: "B-"
      #     net: GND
      trrs:
        what: trrs_tight
        where:
          ref:
            - matrix_inner2_top
          shift: [2, 50]
          rotate: 0
        params:
          reverse: true
          symmetric: false
          # The naming of the nets on this footprint is different from the Corne schematics.
          A: ""
          B: VCC
          C: GND
          D: P0
      # jumper_l:
      #   what: jumper
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0,23.5]
      #     rotate: 270
      #   params:
      #     side: B
      #     from: Bplus
      #     to: RAW
      # jumper_r:
      #   what: jumper
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 23.5]
      #     rotate: 270
      #   params:
      #     side: F
      #     from: Bplus
      #     to: RAW
      # slider_l:
      #   what: slider_threeway
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 30]
      #     rotate: 270
      #   params:
      #     side: F
      #     from: RAW
      #     left: Bplus
      #     right: ''
      # slider_r:
      #   what: slider_threeway
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 30]
      #     rotate: 270
      #   params:
      #     side: B
      #     from: RAW
      #     left: ''
      #     right: Bplus
      # reset:
      #   what: reset_button
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 17]
      #     rotate: 270
      #   params:
      #     from: GND
      #     to: RST
      info_l:
        what: text
        where:
          ref:
            - matrix_inner2_number
          shift: [-.25kx, .75ky]
        params:
          text: "orthosplit75 v0.1\\nby unseenforce"
          justify: left
      info_r:
        what: text
        where:
          ref:
            - matrix_inner2_number
          shift: [-0.25 kx, .75ky]
        params:
          layer: B.SilkS
          text: "orthosplit75 v0.1\\nby unseenforce"
          justify: right mirror
cases:
  plate_stl:
    - name: plate
      operation: add
      extrude: 1.2
  pcb_stl:
    - name: base_outline
      operation: add
      extrude: 1.6
    - name: switches
      operation: subtract
      extrude: 1.6