meta:
  engine: 4.0.4
  name: samoklava
  version: 0.3
  author: soundmonnster
  url: https://github.com/soundmonster/samoklava
units:
  kx: cx
  ky: cy
  px: 2
  py: 2
  key_x: cx
  key_y: cy
  padding_x: 2
  padding_y: 2
  slop_x: .2
  slop_y: .2
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
      diode:
        type: diode
        nets:
          from: =colrow
          to: =row_net
        anchor:
          shift: [0, -5]
  zones:
    matrix:
      key.padding: ky
      columns:
        backspace:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_backspace
        caps:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_caps
        pinky:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_pinky
        ring:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_ring
        middle:
          key:
            stagger: 0 ky
            spread: kx
            column_net: col_middle
        index:
          key:
            stagger: -0 ky
            spread: kx
            column_net: col_index
        inner:
          key:
            stagger: -0 ky
            spread: kx
            column_net: col_inner
        inner2:
          key:
            stagger: -0 ky
            spread: kx
            column_net: col_inner2
      rows:
        ctrl:
          row_net: row_ctrl
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
        number:
          row_net: row_number
outlines:
  # board dimensions according to JLCPCB: 122.28 mm x 101.05 mm
  raw:
    - what: polygon
      asym: source
      fillet: px
      points:
        - ref: matrix_backspace_number # top left
          shift: [-(key_x/2 + padding_x), key_x/2 + padding_y]
        - ref: matrix_backspace_ctrl # bottom left
          shift: [-(key_x/2 + padding_x), -(key_x/2 + padding_y)]
        - ref: matrix_inner2_ctrl # bottom right
          shift: [(key_x/2 + padding_x), -(key_x/2 + padding_y)]
        - ref: matrix_inner2_number # top right
          shift: [(key_x/2 + padding_x), (key_x/2 + padding_y)]
  raw_unfileted:
    - what: rectangle
      where: true
      asym: source
      size: [kx + px + .4, ky + py + .4]
  raw_wall:
    - what: outline
      name: raw
      expand: 2
  controller_area:
    - what: rectangle
      where:
        - ref: matrix_inner2_top
          # re-tranalte to new anchor position
          shift: [-56/2 + .5kx + 1, 30/2 + 1.5ky - 3]
      size: [56, 30]
      corner: px
  controller_area_unfileted:
    - what: rectangle
      where:
        - ref: matrix_inner2_top
          # re-tranalte to new anchor position
          shift: [-56/2 + .5kx + 1, 30/2 + 1.5ky - 3]
      size: [56.4, 30.4]
  controller_area_wall:
    - what: rectangle
      where:
        - ref: matrix_inner2_top
          # re-tranalte to new anchor position
          shift: [-56/2 + .5kx + 1, 30/2 + 1.5ky - 3]
      size: [58.4, 32.4]
      corner: px
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 13.8 # mm
  switches_clip:
    - what: rectangle
      where: true
      asym: source
      size: [14.7, 13.8] # mm 14.5 + .2 for slop
  unused_left_switches:
    backspace_ctrl:
      what: rectangle
      size: 14.7 # mm
      where:
        - ref: matrix_backspace_ctrl
    backspace_bottom:
      what: rectangle
      size: 14.7 # mm
      where:
        - ref: matrix_backspace_bottom
    backspace_home:
      what: rectangle
      size: 14.7 # mm
      where:
        - ref: matrix_backspace_home
    backspace_top:
      what: rectangle
      size: 14.7 # mm
      where:
        - ref: matrix_backspace_top
    backspace_number:
      what: rectangle
      size: 14.7 # mm
      where:
        - ref: matrix_backspace_number
  unused_right_switches:
    backspace_bottom:
      what: rectangle
      size: 14.7 # mm
      where:
        - ref: matrix_backspace_bottom
  switches_test_wall:
    - what: rectangle
      size: [16.7, 15.8] # mm 14.5 + .2 for slop
  switches_test:
    - what: rectangle
      size: 13.8
  switches_clip_test:
    - what: rectangle
      size: [14.7, 13.8] # mm 14.5 + .2 for slop
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [kx, ky] 
      corner: 1
  keywell:
    - "raw"
    # - "+patch_inner"
    # - "+patch_outer"
  base_outline:
    - "keywell"
    - "+controller_area"
    # - "+patch_controller"
  base_outline_unfileted:
    - "raw_unfileted"
    - "+controller_area_unfileted"
    # - "+patch_controller"
  screw_holes:
    top_left:
      what: circle
      where:
        - ref: matrix_ring_home
          shift: [-0.5 kx, 0 ky]
      radius: 1.05
    bottom_left:
      what: circle
      where:
        - ref: matrix_pinky_bottom
          shift: [0.5 kx, 0]
      radius: 1.05
    top_right:
      what: circle
      where:
        - ref: matrix_inner2_top
          shift: [-0.5 kx, 0]
      radius: 1.05
  mounting_holes:
    $extends: outlines.screw_holes
    top_left:
      radius: 2.05
    bottom_left:
      radius: 2.05
    top_right:
      radius: 2.05
  wall:
    - "raw_wall"
    - "controller_area_wall"
  bottom_outline:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-screw_holes"
  plate:
    - "keywell"
    - "-switches"
    - "-screw_holes"
  left_plate:
    - "keywell"
    - "-switches"
    - "-screw_holes"
    - "unused_left_switches"
  pcb:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-mounting_holes"
pcbs:
  top_plate:
    outlines:
      edge:
        outline: plate
        layer: Edge.Cuts
    footprints:
      jlc_order_number:
        what: text
        where:
          ref:
            - matrix_ring_home
          shift: [-0.25 kx, 0.5 ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: left
  bottom_plate:
    outlines:
      edge:
        outline: bottom_outline
        layer: Edge.Cuts
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
    footprints:
      choc_hotswap:
        what: choc
        where:
          - /matrix_.*/
        params:
          hotswap: true
          reverse: true
          keycaps: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: smd_diode
        where:
          - /matrix_.*/
        adjust.shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      mcu_r:
        what: promicro_flippable
        where:
          ref:
            - matrix_inner2_top
          shift: [-24, 38]
          rotate: 0
        params:
          orientation: up
          silk_layer: B.SilkS
          P3: row_number
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_ctrl
          P10: col_inner2
          P16: col_inner
          P14: col_index
          P15: col_middle
          P18: col_ring
          P19: col_pinky
          P20: col_caps
          P21: col_backspace
      mcu_l:
        what: promicro_flippable
        where:
          ref:
            - matrix_inner2_top
          shift: [-25.25, 40.5]
          rotate: 0
        params:
          orientation: down
          silk_layer: F.SilkS
#      pad_plus:
#        what: pad
#        where:
#          ref:
#            - matrix_inner_top
#          shift: [23, -6]
#          rotate: 0
#        params:
#          front: true
#          back: true
#          width: 1.5
#          height: 1.5
#          text: "B+"
#          net: Bplus
#      pad_minus:
#        what: pad
#        where:
#          ref:
#            - matrix_inner_top
#          shift: [23, -3]
#          rotate: 0
#        params:
#          front: true
#          back: true
#          width: 1.5
#          height: 1.5
#          text: "B-"
#          net: GND
      trrs:
        what: trrs_tight
        where:
          ref:
            - matrix_inner2_top
          shift: [2, 50]
          rotate: 0
        params:
          reverse: true
          symmetric: false
          # The naming of the nets on this footprint is different from the Corne schematics.
          A: ""
          B: VCC
          C: GND
          D: P0
      # jumper_l:
      #   what: jumper
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0,23.5]
      #     rotate: 270
      #   params:
      #     side: B
      #     from: Bplus
      #     to: RAW
      # jumper_r:
      #   what: jumper
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 23.5]
      #     rotate: 270
      #   params:
      #     side: F
      #     from: Bplus
      #     to: RAW
      # slider_l:
      #   what: slider_threeway
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 30]
      #     rotate: 270
      #   params:
      #     side: F
      #     from: RAW
      #     left: Bplus
      #     right: ''
      # slider_r:
      #   what: slider_threeway
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 30]
      #     rotate: 270
      #   params:
      #     side: B
      #     from: RAW
      #     left: ''
      #     right: Bplus
      # reset:
      #   what: reset_button
      #   where:
      #     ref:
      #       - matrix_inner2_bottom
      #     shift: [0, 17]
      #     rotate: 270
      #   params:
      #     from: GND
      #     to: RST
      info_l:
        what: text
        where:
          ref:
            - matrix_inner2_number
          shift: [-.25kx, .75ky]
        params:
          text: "orthosplit75 v0.2\\nby unseenforce"
          justify: left
      info_r:
        what: text
        where:
          ref:
            - matrix_inner2_number
          shift: [-0.25 kx, .75ky]
        params:
          layer: B.SilkS
          text: "orthosplit75 v0.2\\nby unseenforce"
          justify: right mirror
cases:
  left_plate_rotated_stl:
    - name: plate
      operation: add
      extrude: 2.2
    - name: switches_clip
      operation: subtract
      extrude: 0.92 # + .2 for slop
    - name: unused_left_switches
      operation: add
      extrude: 2.2
  left_plate_stl:
    - what: case
      name: left_plate_rotated_stl
      rotate: [180, 0, 0]
  right_plate_stl:
    - name: plate
      operation: add
      extrude: 2.2
    - name: switches_clip
      operation: subtract
      shift: [0, 0, 1.28] # -.2 for slop
      extrude: 0.9
    - name: unused_right_switches
      operation: add
      extrude: 2.2
  switch_test_stl:
    - name: switches_test_wall
      operation: add
      extrude: 2.2
    - name: switches_test
      operation: subtract
      extrude: 2.2
    - name: switches_clip_test
      operation: subtract
      shift: [0, 0, 1.28] # -.2 for slop
      extrude: 0.9
  tester_stl:
    - name: plate
      operation: add
      extrude: 4.85 # 2.2 + 2.65
    - name: switches_clip
      operation: subtract
      shift: [0, 0, 1.3]
      extrude: 3.55  # 0.9 + 2.65
  base_stl:
    - name: base_outline
      operation: add
      extrude: 2.2
  total_area:
    - name: raw_wall
      operation: add
      extrude: 7 # floor thickness 1mm, 6mm for height
    - name: controller_area_wall
      operation: add
      extrude: 7 # floor thickness 1mm, 6mm for height
  inner_wall: 
    - name: base_outline_unfileted
      extrude:  7 # floor thickness 1mm, 6mm for height
  wall:
    - what: case
      name: total_area
      operation: add
    - what: case
      name: inner_wall
      operation: subtract
  floor:
    - name: base_outline_unfileted
      operation: add
      extrude: 1
  case_stl:
    - what: case
      name: wall
      operation: add
    - what: case
      name: floor
      operation: add